[
    {
        "ASN": "",
        "Actual Ship Code": "",
        "Actual Ship Mode": "",
        "Agreement ID": "",
        "Amount": 1116.5,
        "BUID": "10250",
        "BillingCustomerName": "dell",
        "Build Facility": "",
        "CFI Flag": "N",
        "City Code": "",
        "Country": "FR",
        "Create Date": "2025-07-31T14:02:46",
        "Currency Code": "EUR",
        "Customer Name Ext": "",
        "Customer Num": "P10013117394",
        "Customer Po Number": "",
        "CustomerName": "",
        "Delivery City": "",
        "Dell Blanket Po Num": "",
        "Destination": "",
        "DomsStatus": "PP",
        "Dp ID": "8040072833",
        "FO ID": "7356670668332126209",
        "Facility": "",
        "First Leg Ship Mode": "",
        "Fulfillment ID": "3000072908",
        "Fulfillment Status": "PENDFULFILL",
        "Has Software": "",
        "IP Date": "",
        "InstallInstruction2": "",
        "Is Last Leg": "",
        "Is Multi Pack": "",
        "LOB": "",
        "Location Number": "01",
        "MN Date": "",
        "Make WoAck": "",
        "Manifest Date": "",
        "Manifest ID": "",
        "Mcid": "",
        "Merge Type": "ATO-DIRECT",
        "Must Arrive By Date": "",
        "OIC ID": "YiJV2m4OEfCuepNVwpMAgg",
        "Ofs Status": "PENDFULFILL",
        "Ofs Status Code": "PP",
        "Order Age": "2025-07-31T05:28:02",
        "Order Amount usd": 0.0,
        "Order Date": "2025-07-31T05:28:02",
        "Order Type": "Standard Order",
        "Order Update Date": "2025-07-31T14:02:46.125917",
        "Order Vol Wt": "",
        "Origin": "",
        "PP Date": "2025-07-31T13:02:46",
        "PP ID": "",
        "Payment Term Code": "IMMEDIATE",
        "Product Lob": "",
        "Rate Usd Transactional": 0.0,
        "Reassigned Ip Date": "PP",
        "Region Code": "EMEA",
        "Req Ship Code": "IY",
        "Revised Delivery Date": "",
        "SC Date": "",
        "SN Number": "",
        "Sales Order ID": "8040072833",
        "Sales Rep Name": "",
        "Ship By Date": "",
        "Ship Code": "IY",
        "Ship From Mcid": "",
        "Ship To Mcid": "",
        "ShipToAddress1": "",
        "ShipToAddress2": "",
        "ShipToCompany": "",
        "ShipToPhone": "",
        "ShipToPostal": "",
        "Shipping Country": "IE",
        "ShippingCityCode": "",
        "ShippingContactName": "",
        "ShippingCustName": "",
        "ShippingStateCode": "",
        "Si Number": "",
        "Source System ID": "OLRECOMM",
        "Source System Status": "PP",
        "State Code": "",
        "Svc Tag": "",
        "System Qty": 1,
        "Target Delivery Date": "",
        "Tax Regstrn Num": "",
        "Tie Number": 23,
        "Total Box Count": "",
        "Total Gross Weight": "",
        "Total Volumetric Weight": "",
        "Update Date": "2025-07-31T14:02:46",
        "WO ID": "",
        "Way Bill Number": "",
        "Wo Otm Enable": "",
        "Wo Ship Mode": "",
        "logs": {
            "urls": [],
            "time": []
        }
    }
]
