[
    {
        "Count ": 2
    },
    [
        {
            "Agreement ID": "",
            "Amount": "4395",
            "BUID": "10826",
            "BillingCustomerName": "NKT A/S",
            "City Code": "",
            "Country": "UK",
            "Currency Code": "DKK",
            "Customer Name Ext": "",
            "Customer Num": "D11202973527",
            "Customer Po Number": "",
            "CustomerName": "NKT A/S",
            "DOMS Status": "PP",
            "Delivery City": "",
            "Dp ID": "4330142526",
            "FO ID": "7374295748266176512",
            "Facility": "",
            "Fulfillment ID": "5601412322",
            "Fulfillment Status": "PENDFULFILL",
            "IP Date": "",
            "InstallInstruction2": "",
            "LOB": "Laptop",
            "Location Number": "01",
            "MN Date": "",
            "Manifest Date": "",
            "Merge Type": "ATO-INDIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "PENDFULFILL",
            "OFS Status Code": "PP",
            "OIC ID": "4158f306-befc-4dea-8356-9a62e1aacf1c",
            "Order Age": "2025-09-09 06:01:13",
            "Order Amount usd": "0",
            "Order Date": "2025-09-09 06:01:13",
            "Order Type": "Standard Order",
            "PP Date": "2025-09-18 04:18:32",
            "Payment Term Code": "Prepaid",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "PP",
            "Region Code": "EMEA",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "1900-01-01 00:00:00",
            "SC Date": "",
            "Sales Order ID": "4330142526",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "ShipToAddress1": "Vibeholms Alle 20\\, 2",
            "ShipToAddress2": "",
            "ShipToCompany": "NKT A/S",
            "ShipToPhone": "",
            "ShipToPostal": "2605",
            "Shipping Country": "UK",
            "ShippingCityCode": "",
            "ShippingContactName": "x y xqnbuld",
            "ShippingCustName": "NKT A/S",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "PP",
            "State Code": "",
            "System Qty": "1",
            "Tax Regstrn Num": "",
            "Tie Number": "1"
        },
        {
            "Agreement ID": "",
            "Amount": "4395",
            "BUID": "10826",
            "BillingCustomerName": "NKT A/S",
            "City Code": "",
            "Country": "UK",
            "Currency Code": "DKK",
            "Customer Name Ext": "",
            "Customer Num": "D11202973527",
            "Customer Po Number": "",
            "CustomerName": "NKT A/S",
            "DOMS Status": "PP",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "4330142526",
            "FO ID": "7374295748266176512",
            "Facility": "",
            "Fulfillment ID": "5601412322",
            "Fulfillment Status": "PENDFULFILL",
            "Has Software": false,
            "IP Date": "",
            "InstallInstruction2": "",
            "Is Last Leg": "Y",
            "Is Multipack": "",
            "LOB": "Laptop",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "ATO-INDIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "PENDFULFILL",
            "OFS Status Code": "PP",
            "OIC ID": "4158f306-befc-4dea-8356-9a62e1aacf1c",
            "Order Age": "2025-09-09 06:01:13",
            "Order Amount usd": "0",
            "Order Date": "2025-09-09 06:01:13",
            "Order Type": "Standard Order",
            "PP Date": "2025-09-18 04:18:32",
            "Payment Term Code": "Prepaid",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "PP",
            "Region Code": "EMEA",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "1900-01-01 00:00:00",
            "SC Date": "",
            "Sales Order ID": "4330142526",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "FG1",
            "Ship To Facility": "CUST",
            "ShipToAddress1": "Vibeholms Alle 20\\, 2",
            "ShipToAddress2": "",
            "ShipToCompany": "NKT A/S",
            "ShipToPhone": "",
            "ShipToPostal": "2605",
            "Shipping Country": "UK",
            "ShippingCityCode": "",
            "ShippingContactName": "x y xqnbuld",
            "ShippingCustName": "NKT A/S",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "PP",
            "State Code": "",
            "System Qty": "1",
            "Tax Regstrn Num": "",
            "Tie Number": "1",
            "WO OTM Enabled": "",
            "WO Ship Mode": "GD",
            "WO_ID": "65777"
        },
        {
            "Agreement ID": "",
            "Amount": "4395",
            "BUID": "10826",
            "BillingCustomerName": "NKT A/S",
            "City Code": "",
            "Country": "UK",
            "Currency Code": "DKK",
            "Customer Name Ext": "",
            "Customer Num": "D11202973527",
            "Customer Po Number": "",
            "CustomerName": "NKT A/S",
            "DOMS Status": "PP",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "4330142526",
            "FO ID": "7374295748266176512",
            "Facility": "",
            "Fulfillment ID": "5601412322",
            "Fulfillment Status": "PENDFULFILL",
            "Has Software": false,
            "IP Date": "",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Laptop",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "ATO-INDIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "PENDFULFILL",
            "OFS Status Code": "PP",
            "OIC ID": "4158f306-befc-4dea-8356-9a62e1aacf1c",
            "Order Age": "2025-09-09 06:01:13",
            "Order Amount usd": "0",
            "Order Date": "2025-09-09 06:01:13",
            "Order Type": "Standard Order",
            "PP Date": "2025-09-18 04:18:32",
            "Payment Term Code": "Prepaid",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "PP",
            "Region Code": "EMEA",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "1900-01-01 00:00:00",
            "SC Date": "",
            "Sales Order ID": "4330142526",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "WCD",
            "Ship To Facility": "FG1",
            "ShipToAddress1": "Vibeholms Alle 20\\, 2",
            "ShipToAddress2": "",
            "ShipToCompany": "NKT A/S",
            "ShipToPhone": "",
            "ShipToPostal": "2605",
            "Shipping Country": "UK",
            "ShippingCityCode": "",
            "ShippingContactName": "x y xqnbuld",
            "ShippingCustName": "NKT A/S",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "PP",
            "State Code": "",
            "System Qty": "1",
            "Tax Regstrn Num": "",
            "Tie Number": "1",
            "WO OTM Enabled": "",
            "WO Ship Mode": "GD",
            "WO_ID": "65788"
        }
    ]
]
