[
    {
        "Count ": 1
    },
    [
        {
            "Agreement ID": "",
            "Amount": "11353.88",
            "BUID": "10036",
            "BillingCustomerName": "Qantas Airways Limited",
            "City Code": "",
            "Country": "AU",
            "Currency Code": "AUD",
            "Customer Name Ext": "",
            "Customer Num": "D11200523232",
            "Customer Po Number": "",
            "CustomerName": "Qantas Airways Limited",
            "DOMS Status": "SC",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "8040070632",
            "FO ID": "7355860096558333953",
            "Facility": "BX2",
            "Fulfillment ID": "3000070327",
            "Fulfillment Status": "Ship Confirm",
            "Has Software": false,
            "IP Date": "",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Dell UltraSharp Monitors",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "PTO-DIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "Ship Confirm",
            "OFS Status Code": "SC",
            "OIC ID": "ZTmNBGxMEfCHJe_Jjx4dAA",
            "Order Age": "2025-07-29 06:59:04",
            "Order Amount usd": "0",
            "Order Date": "2025-07-29 06:59:04",
            "Order Type": "Standard Order",
            "PP Date": "",
            "Payment Term Code": "IMMEDIATE",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "SC",
            "Region Code": "APJ",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "",
            "SC Date": "2025-07-29 07:35:16",
            "Sales Order ID": "8040070632",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "",
            "Ship To Facility": "",
            "ShipToAddress1": "10 Bourke Road",
            "ShipToAddress2": "",
            "ShipToCompany": "Qantas Airways Limited",
            "ShipToPhone": "61-02261111818",
            "ShipToPostal": "2020",
            "Shipping Country": "AU",
            "ShippingCityCode": "",
            "ShippingContactName": "Vinay Kumar",
            "ShippingCustName": "Qantas Airways Limited",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "SC",
            "State Code": "",
            "System Qty": "1",
            "Tax Regstrn Num": "",
            "Tie Number": "1",
            "WO OTM Enabled": "",
            "WO Ship Mode": "",
            "WO_ID": "1888314027"
        },
        {
            "Agreement ID": "",
            "Amount": "11353.88",
            "BUID": "10036",
            "BillingCustomerName": "Qantas Airways Limited",
            "City Code": "",
            "Country": "AU",
            "Currency Code": "AUD",
            "Customer Name Ext": "",
            "Customer Num": "D11200523232",
            "Customer Po Number": "",
            "CustomerName": "Qantas Airways Limited",
            "DOMS Status": "SC",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "8040070632",
            "FO ID": "7355860096558333953",
            "Facility": "BX2",
            "Fulfillment ID": "3000070327",
            "Fulfillment Status": "Ship Confirm",
            "Has Software": false,
            "IP Date": "",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Dell UltraSharp Monitors",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "PTO-DIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "Ship Confirm",
            "OFS Status Code": "SC",
            "OIC ID": "ZTmNBGxMEfCHJe_Jjx4dAA",
            "Order Age": "2025-07-29 06:59:04",
            "Order Amount usd": "0",
            "Order Date": "2025-07-29 06:59:04",
            "Order Type": "Standard Order",
            "PP Date": "",
            "Payment Term Code": "IMMEDIATE",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "SC",
            "Region Code": "APJ",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "",
            "SC Date": "2025-07-29 07:35:16",
            "Sales Order ID": "8040070632",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "",
            "Ship To Facility": "",
            "ShipToAddress1": "10 Bourke Road",
            "ShipToAddress2": "",
            "ShipToCompany": "Qantas Airways Limited",
            "ShipToPhone": "61-02261111818",
            "ShipToPostal": "2020",
            "Shipping Country": "AU",
            "ShippingCityCode": "",
            "ShippingContactName": "Vinay Kumar",
            "ShippingCustName": "Qantas Airways Limited",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "SC",
            "State Code": "",
            "System Qty": "1",
            "Tax Regstrn Num": "",
            "Tie Number": "1",
            "WO OTM Enabled": "",
            "WO Ship Mode": "",
            "WO_ID": "1122192942"
        },
        {
            "Agreement ID": "",
            "Amount": "11353.88",
            "BUID": "10036",
            "BillingCustomerName": "Qantas Airways Limited",
            "City Code": "",
            "Country": "AU",
            "Currency Code": "AUD",
            "Customer Name Ext": "",
            "Customer Num": "D11200523232",
            "Customer Po Number": "",
            "CustomerName": "Qantas Airways Limited",
            "DOMS Status": "SC",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "8040070632",
            "FO ID": "7355860096558333953",
            "Facility": "BX2",
            "Fulfillment ID": "3000070327",
            "Fulfillment Status": "Ship Confirm",
            "Has Software": false,
            "IP Date": "",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Dell UltraSharp Monitors",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "PTO-DIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "Ship Confirm",
            "OFS Status Code": "SC",
            "OIC ID": "ZTmNBGxMEfCHJe_Jjx4dAA",
            "Order Age": "2025-07-29 06:59:04",
            "Order Amount usd": "0",
            "Order Date": "2025-07-29 06:59:04",
            "Order Type": "Standard Order",
            "PP Date": "",
            "Payment Term Code": "IMMEDIATE",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "SC",
            "Region Code": "APJ",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "",
            "SC Date": "2025-07-29 07:35:16",
            "Sales Order ID": "8040070632",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "",
            "Ship To Facility": "",
            "ShipToAddress1": "10 Bourke Road",
            "ShipToAddress2": "",
            "ShipToCompany": "Qantas Airways Limited",
            "ShipToPhone": "61-02261111818",
            "ShipToPostal": "2020",
            "Shipping Country": "AU",
            "ShippingCityCode": "",
            "ShippingContactName": "Vinay Kumar",
            "ShippingCustName": "Qantas Airways Limited",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "SC",
            "State Code": "",
            "System Qty": "1",
            "Tax Regstrn Num": "",
            "Tie Number": "1",
            "WO OTM Enabled": "",
            "WO Ship Mode": "",
            "WO_ID": "1127194521"
        },
        {
            "Agreement ID": "",
            "Amount": "11353.88",
            "BUID": "10036",
            "BillingCustomerName": "Qantas Airways Limited",
            "City Code": "",
            "Country": "AU",
            "Currency Code": "AUD",
            "Customer Name Ext": "",
            "Customer Num": "D11200523232",
            "Customer Po Number": "",
            "CustomerName": "Qantas Airways Limited",
            "DOMS Status": "IP",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "8040070632",
            "FO ID": "7355928803984830465",
            "Facility": "WCD",
            "Fulfillment ID": "3000070326",
            "Fulfillment Status": "In Production",
            "Has Software": false,
            "IP Date": "2025-07-29 13:20:07",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Inspiron 14 5440",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "ATO-INDIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "In Production",
            "OFS Status Code": "IP",
            "OIC ID": "_CiIpGxVEfCLGBGxs3YlMQ",
            "Order Age": "2025-07-29 06:59:04",
            "Order Amount usd": "0",
            "Order Date": "2025-07-29 06:59:04",
            "Order Type": "Standard Order",
            "PP Date": "",
            "Payment Term Code": "IMMEDIATE",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "IP",
            "Region Code": "APJ",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "",
            "SC Date": "",
            "Sales Order ID": "8040070632",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "",
            "Ship To Facility": "",
            "ShipToAddress1": "10 Bourke Road",
            "ShipToAddress2": "",
            "ShipToCompany": "Qantas Airways Limited",
            "ShipToPhone": "61-02261111818",
            "ShipToPostal": "2020",
            "Shipping Country": "AU",
            "ShippingCityCode": "",
            "ShippingContactName": "Vinay Kumar",
            "ShippingCustName": "Qantas Airways Limited",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "IP",
            "State Code": "",
            "System Qty": "5",
            "Tax Regstrn Num": "",
            "Tie Number": "23",
            "WO OTM Enabled": "",
            "WO Ship Mode": "",
            "WO_ID": "1888314027"
        },
        {
            "Agreement ID": "",
            "Amount": "11353.88",
            "BUID": "10036",
            "BillingCustomerName": "Qantas Airways Limited",
            "City Code": "",
            "Country": "AU",
            "Currency Code": "AUD",
            "Customer Name Ext": "",
            "Customer Num": "D11200523232",
            "Customer Po Number": "",
            "CustomerName": "Qantas Airways Limited",
            "DOMS Status": "IP",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "8040070632",
            "FO ID": "7355928803984830465",
            "Facility": "WCD",
            "Fulfillment ID": "3000070326",
            "Fulfillment Status": "In Production",
            "Has Software": false,
            "IP Date": "2025-07-29 13:20:07",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Inspiron 14 5440",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "ATO-INDIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "In Production",
            "OFS Status Code": "IP",
            "OIC ID": "_CiIpGxVEfCLGBGxs3YlMQ",
            "Order Age": "2025-07-29 06:59:04",
            "Order Amount usd": "0",
            "Order Date": "2025-07-29 06:59:04",
            "Order Type": "Standard Order",
            "PP Date": "",
            "Payment Term Code": "IMMEDIATE",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "IP",
            "Region Code": "APJ",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "",
            "SC Date": "",
            "Sales Order ID": "8040070632",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "",
            "Ship To Facility": "",
            "ShipToAddress1": "10 Bourke Road",
            "ShipToAddress2": "",
            "ShipToCompany": "Qantas Airways Limited",
            "ShipToPhone": "61-02261111818",
            "ShipToPostal": "2020",
            "Shipping Country": "AU",
            "ShippingCityCode": "",
            "ShippingContactName": "Vinay Kumar",
            "ShippingCustName": "Qantas Airways Limited",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "IP",
            "State Code": "",
            "System Qty": "5",
            "Tax Regstrn Num": "",
            "Tie Number": "23",
            "WO OTM Enabled": "",
            "WO Ship Mode": "",
            "WO_ID": "1122192942"
        },
        {
            "Agreement ID": "",
            "Amount": "11353.88",
            "BUID": "10036",
            "BillingCustomerName": "Qantas Airways Limited",
            "City Code": "",
            "Country": "AU",
            "Currency Code": "AUD",
            "Customer Name Ext": "",
            "Customer Num": "D11200523232",
            "Customer Po Number": "",
            "CustomerName": "Qantas Airways Limited",
            "DOMS Status": "IP",
            "Delivery City": "",
            "Dell Blanket PO Num": "",
            "Dp ID": "8040070632",
            "FO ID": "7355928803984830465",
            "Facility": "WCD",
            "Fulfillment ID": "3000070326",
            "Fulfillment Status": "In Production",
            "Has Software": false,
            "IP Date": "2025-07-29 13:20:07",
            "InstallInstruction2": "",
            "Is Last Leg": "N",
            "Is Multipack": "",
            "LOB": "Inspiron 14 5440",
            "Location Number": "01",
            "MCID Value": "",
            "MN Date": "",
            "Make WO Ack Date": "",
            "Manifest Date": "",
            "Merge Type": "ATO-INDIRECT",
            "Must Arrive By Date": "",
            "OFS Status": "In Production",
            "OFS Status Code": "IP",
            "OIC ID": "_CiIpGxVEfCLGBGxs3YlMQ",
            "Order Age": "2025-07-29 06:59:04",
            "Order Amount usd": "0",
            "Order Date": "2025-07-29 06:59:04",
            "Order Type": "Standard Order",
            "PP Date": "",
            "Payment Term Code": "IMMEDIATE",
            "Rate Usd Transactional": "0",
            "Reassigned IP Date": "IP",
            "Region Code": "APJ",
            "Req Ship Code": "IY",
            "Revised Delivery Date": "",
            "SC Date": "",
            "Sales Order ID": "8040070632",
            "Sales Rep Name": "",
            "Ship By Date": "",
            "Ship Code": "IY",
            "Ship From MCID": "",
            "Ship To Facility": "",
            "ShipToAddress1": "10 Bourke Road",
            "ShipToAddress2": "",
            "ShipToCompany": "Qantas Airways Limited",
            "ShipToPhone": "61-02261111818",
            "ShipToPostal": "2020",
            "Shipping Country": "AU",
            "ShippingCityCode": "",
            "ShippingContactName": "Vinay Kumar",
            "ShippingCustName": "Qantas Airways Limited",
            "ShippingStateCode": "",
            "Si Number": "",
            "Source System ID": "DSP",
            "Source System Status": "IP",
            "State Code": "",
            "System Qty": "5",
            "Tax Regstrn Num": "",
            "Tie Number": "23",
            "WO OTM Enabled": "",
            "WO Ship Mode": "",
            "WO_ID": "1127194521"
        }
    ]
]
