Column Name	Contact Type
BillingCustomerName	BILLING
CustomerName	SHIPPING
InstallInstruction2	ATTRIBUTE_NAME = 'INSTALL_INSTR2'
ShippingCityCode	SHIPPING
ShippingContactName	SHIPPING
ShippingCustName	SHIPPING
ShippingStateCode	SHIPPING
ShipToAddress1	SHIPPING
ShipToAddress2	SHIPPING
ShipToCompany	SHIPPING
ShipToPhone	SHIPPING
ShipToPostal	SHIPPING

BillingCustomerName	getSoheaderBySoids/address/companyName
getSoheaderBySoids/address/contact/contactType
CustomerName	getSoheaderBySoids/address/companyName
getSoheaderBySoids/address/contact/contactType
InstallInstruction2	getFulfillmentsById/salesOrderLines/specialinstructions/specialInstructionId
getFulfillmentsById/salesOrderLines/specialinstructions/specialInstructionType
ShippingCityCode	getSoheaderBySoids/address/cityCode
getSoheaderBySoids/address/contact/contactType
ShippingContactName	getSoheaderBySoids/address/firstName
getSoheaderBySoids/address/lastName
getSoheaderBySoids/address/contact/contactType
ShippingCustName	getSoheaderBySoids/address/companyName
getSoheaderBySoids/address/contact/contactType
ShippingStateCode	getSoheaderBySoids/address/stateCode
getSoheaderBySoids/address/contact/contactType
ShipToAddress1	getSoheaderBySoids/address/addressLine1
getSoheaderBySoids/address/contact/contactType
ShipToAddress2	getSoheaderBySoids/address/addressLine2
getSoheaderBySoids/address/contact/contactType
ShipToCompany	getSoheaderBySoids/address/companyName
getSoheaderBySoids/address/contact/contactType
ShipToPhone	getSoheaderBySoids/address/contact/contactType
getSoheaderBySoids/address/phone/phoneNumber
ShipToPostal	getSoheaderBySoids/address/postalCode
getSoheaderBySoids/address/contact/contactType
